name: node-build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine
    steps:
      - uses: actions/checkout@v4

      - run: yarn install --frozen-lockfile
      - run: yarn build
